### ISSUE TITLE
关于index.js最后一行代码

### ISSUE THREAD

**Issue by xuyuan923** [doving/webAudio#1]
index.js最后不需要加$('#volume')[0].onchange(); 因为监听到volume变化，就已经可以执行changeVolume函数了呀。我自己测试不加也是可行的

**Comment by doving** [comment]
需要加的，同学，为了初始化设置gainNode.gain.value的值。
因为页面初始化时type=range控件已经设置了默认是value值（不为1），而gainNode.gain.value默认为1，在不改变range控件的值时监听程序也就不会调用，所以为了使默认的设置生效，需要先调用一次监听程序

**Comment by xuyuan923** [comment]
知道了，谢谢回复！
