### ISSUE TITLE
关于 node_modules

### ISSUE THREAD

**Issue by XadillaX** [doving/webAudio#2]
实际上这个目录不需要在 git 目录里面，而是 clone 之后通过 `npm` 进行安装依赖的。

**Comment by doving** [comment]
嗯嗯嗯，是的是的，谢谢！其实我本来只准备将前端的代码传到git 上的，因为node在其中扮演的角色其实一点也不重要，所以也没考虑太多。多谢指正了，愿多交流，感激哦～～～
