### ISSUE TITLE
怎么下载要50多mb

### ISSUE THREAD

**Issue by Xia-lj** [doving/webAudio#5]
这个跟上课学的 不一样啊。html文件在哪？？怎么打开啊。

**Comment by doving** [comment]
几乎是一样的啊，运行打开方式就是node server的运行  进入项目先npm install 安装依赖，然后node bin/www 最好装个supervisor 运行 supervisor bin/www

**Comment by Xia-lj** [comment]
谢谢doving
通过视频教程  不下数10边 ，终于在本地 可以播放了。>npm start  http://127.0.0.1:3000 本人没基础问的问题比较肤浅，别建议。“我打个 Funation 还需要查看一下字典怎么拼写”。  又有个问题，怎么把他放到 服务器上。。。

**Comment by Xia-lj** [comment]
http://labs.music.baidu.com/
请教一下，如何把这样风格 给拷贝过来。

**Comment by Xia-lj** [comment]
552 occured because of user code error

your package.json file error

pacakge.json must json file and must contain "scripts":{"start":"node xxx.js"}

please modify your package.json and recommit your code

Error Message is

[2015-07-21 18:19:17.812] [ERROR] manager - catch signal SIGTERM, manager will exit
[2015-07-21 18:19:23.118] [ERROR] manager - scripts.start in package.json must contain ".js", but your scripts.start is "node ./bin/www"
get more message, please check manager.log

**Comment by doving** [comment]
你这个是什么，之前heroku上安装依赖出过问题

**Comment by Xia-lj** [comment]
@doving 
那怎么解决。
